version: 2

before:
  hooks:
    - go mod download

builds:
  - id: go-devops
    binary: go-devops
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    dir: ./cmd/go-devops
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.buildTime={{.Date}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

dockers:
  - id: go-devops-amd64
    ids:
      - go-devops
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-amd64"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

  - id: go-devops-arm64
    ids:
      - go-devops
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-arm64"
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"

  - id: go-devops-armv7
    ids:
      - go-devops
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-armv7"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-armv7"
    goos: linux
    goarch: arm
    goarm: '7'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v7"

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-armv7"

  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-armv7"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
